### ISSUE TITLE
PXD-539 ⁃ support bagit as an export format for file nodes

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/peregrine#10]
given a graphql query, if the result nodes are files, return a bdbag with manifest for the file

**Comment by trevars** [comment]
Blocked by lack of information from DCP.

**Comment by trevars** [comment]
There are some new specifications for using BagIt.

**Comment by gneglur** [comment]
#2: UChicago Data Explorer (windmill) → FireCloud
User logs into Windmill using Google credentials (via Fence)
Who can see what data (Authz) is enforced by Windmill (via Fence)
User browses TopMed data, selects a subset and clicks “Export to Firecloud (BDBag)”
Windmill redirects to {firecloud}/import/bdbag?bagit_url={presigned_url}
Firecloud asks user to sign in on their side and and authZ for compute resource
Firecloud use the bagit url to call the bagit url and load the files into the workspace

**Comment by giangbui** [comment]
Spent 8 hours so far

**Comment by philloooo** [comment]
so we should finish it by:
1. push the data to a s3 bucket (the key can be `<userid>/<uuid><unixtime>` )
2. clean up local temp data
3. return presigned url
